<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PoliticalPartiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * Data sourced from Office of the Registrar of Political Parties (ORPP)
     * as of February 2025 - https://orpp.or.ke/list-of-political-parties/
     */
    public function run(): void
    {
        $parties = [
            // Coalition Parties
            [
                'name' => 'Azimio la Umoja One Kenya Coalition Party',
                'abbreviation' => 'Azimio',
                'party_symbol' => 'Five Stars against a blue background',
                'registration_number' => 'CPP/001/2022',
                'is_active' => true,
            ],

            // Major Political Parties (Active in Parliament)
            [
                'name' => 'United Democratic Alliance',
                'abbreviation' => 'UDA',
                'party_symbol' => 'Wheelbarrow',
                'registration_number' => 'PP/087/2021',
                'is_active' => true,
            ],
            [
                'name' => 'Orange Democratic Movement',
                'abbreviation' => 'ODM',
                'party_symbol' => 'Ripe orange',
                'registration_number' => 'PP/001/2007',
                'is_active' => true,
            ],
            [
                'name' => 'Jubilee Party',
                'abbreviation' => 'JP',
                'party_symbol' => 'Dove with an olive branch on its beak',
                'registration_number' => 'PP/062/2016',
                'is_active' => true,
            ],
            [
                'name' => 'Wiper Patriotic Front',
                'abbreviation' => 'Wiper',
                'party_symbol' => 'Umbrella',
                'registration_number' => 'PP/012/2007',
                'is_active' => true,
            ],
            [
                'name' => 'Forum for Restoration of Democracy-Kenya',
                'abbreviation' => 'FORD-K',
                'party_symbol' => 'Lion',
                'registration_number' => 'PP/003/1991',
                'is_active' => true,
            ],
            [
                'name' => 'Kenya African National Union',
                'abbreviation' => 'KANU',
                'party_symbol' => 'Cockerel',
                'registration_number' => 'PP/001/1960',
                'is_active' => true,
            ],

            // Other Registered Political Parties
            [
                'name' => 'The We Alliance Party',
                'abbreviation' => 'TWAP',
                'party_symbol' => 'Five Stars against a blue background',
                'registration_number' => 'PP/091/2025',
                'is_active' => true,
            ],
            [
                'name' => 'Democracy for the Citizens Party',
                'abbreviation' => 'DCP',
                'party_symbol' => 'Balance Scale',
                'registration_number' => 'PP/092/2025',
                'is_active' => true,
            ],
            [
                'name' => 'The Equitable Party',
                'abbreviation' => 'TEP',
                'party_symbol' => 'Balanced Scales',
                'registration_number' => 'PP/089/2024',
                'is_active' => true,
            ],
            [
                'name' => 'Chama ya Mapatano of Kenya',
                'abbreviation' => 'CYMK',
                'party_symbol' => 'Globe Red',
                'registration_number' => 'PP/088/2024',
                'is_active' => true,
            ],
            [
                'name' => 'Universal Unity Party',
                'abbreviation' => 'UUP',
                'party_symbol' => 'Crown',
                'registration_number' => 'PP/086/2024',
                'is_active' => true,
            ],
            [
                'name' => 'Unified Change Party',
                'abbreviation' => 'UCP',
                'party_symbol' => 'Blue Oval with party initials',
                'registration_number' => 'PP/085/2024',
                'is_active' => true,
            ],
            [
                'name' => 'National Democracy Expansion Party',
                'abbreviation' => 'NDEP',
                'party_symbol' => 'Blue Water Tank on White background',
                'registration_number' => 'PP/084/2024',
                'is_active' => true,
            ],
            [
                'name' => 'Green Thinking Action Party',
                'abbreviation' => 'GTAP',
                'party_symbol' => 'Growing Money',
                'registration_number' => 'PP/083/2024',
                'is_active' => true,
            ],
            [
                'name' => 'Party for Growth and Prosperity',
                'abbreviation' => 'PGP',
                'party_symbol' => 'Encircled Trophy',
                'registration_number' => 'PP/082/2024',
                'is_active' => true,
            ],
            [
                'name' => 'Entrust Pioneer Party',
                'abbreviation' => 'EPP',
                'party_symbol' => 'Padlock and Chain',
                'registration_number' => 'PP/081/2024',
                'is_active' => true,
            ],
            [
                'name' => 'Mabadiliko Party of Kenya',
                'abbreviation' => 'MPK',
                'party_symbol' => 'Honey Bee',
                'registration_number' => 'PP/080/2024',
                'is_active' => true,
            ],
            [
                'name' => 'Pamoja African Alliance',
                'abbreviation' => 'PAA',
                'party_symbol' => 'Traditional thatched African Hut',
                'registration_number' => 'PP/079/2024',
                'is_active' => true,
            ],
            [
                'name' => 'Umoja Summit Party',
                'abbreviation' => 'USP',
                'party_symbol' => 'African Pot (Chungu)',
                'registration_number' => 'PP/078/2024',
                'is_active' => true,
            ],
            [
                'name' => 'Kenya Union Party',
                'abbreviation' => 'KUP',
                'party_symbol' => 'Two Vertical Ticks',
                'registration_number' => 'PP/077/2024',
                'is_active' => true,
            ],
            [
                'name' => 'Tujibebe Wakenya Party',
                'abbreviation' => 'TWP',
                'party_symbol' => 'Buffalo',
                'registration_number' => 'PP/076/2024',
                'is_active' => true,
            ],
            [
                'name' => 'Chama Cha Kazi',
                'abbreviation' => 'CCK',
                'party_symbol' => 'Overall coat',
                'registration_number' => 'PP/075/2024',
                'is_active' => true,
            ],
            [
                'name' => 'Party for Peace and Development',
                'abbreviation' => 'PPD',
                'party_symbol' => 'Triangle',
                'registration_number' => 'PP/074/2024',
                'is_active' => true,
            ],
            [
                'name' => 'Democratic Action Party-Kenya',
                'abbreviation' => 'DAP-K',
                'party_symbol' => 'Leopard',
                'registration_number' => 'PP/073/2024',
                'is_active' => true,
            ],
            [
                'name' => 'National Reconstruction Alliance',
                'abbreviation' => 'NRA',
                'party_symbol' => 'Eagle',
                'registration_number' => 'PP/072/2024',
                'is_active' => true,
            ],
            [
                'name' => 'National Ordinary People Empowerment Union',
                'abbreviation' => 'NOPEU',
                'party_symbol' => 'Ladder',
                'registration_number' => 'PP/071/2024',
                'is_active' => true,
            ],
            [
                'name' => 'The Service Party',
                'abbreviation' => 'TSP',
                'party_symbol' => 'Heart shape inscribed inside a circle',
                'registration_number' => 'PP/070/2024',
                'is_active' => true,
            ],
            [
                'name' => 'United Progressive Alliance',
                'abbreviation' => 'UPA',
                'party_symbol' => 'Two-wheeler motorcycle',
                'registration_number' => 'PP/069/2024',
                'is_active' => true,
            ],
            [
                'name' => 'Usawa Kwa Wote',
                'abbreviation' => 'UKW',
                'party_symbol' => 'A cow and milking can',
                'registration_number' => 'PP/068/2024',
                'is_active' => true,
            ],
            [
                'name' => 'United Green Movement',
                'abbreviation' => 'UGM',
                'party_symbol' => 'Unity of purpose against an olive-green background',
                'registration_number' => 'PP/067/2024',
                'is_active' => true,
            ],
            [
                'name' => 'Grand Dream Development Party',
                'abbreviation' => 'GDDP',
                'party_symbol' => 'Sack labelled GDDP Dreams',
                'registration_number' => 'PP/066/2024',
                'is_active' => true,
            ],
            [
                'name' => 'Justice and Freedom Party of Kenya',
                'abbreviation' => 'JFPK',
                'party_symbol' => 'Stretched out hand holding freedom torch',
                'registration_number' => 'PP/065/2024',
                'is_active' => true,
            ],
            [
                'name' => 'Third Way Alliance Kenya',
                'abbreviation' => 'TWA-K',
                'party_symbol' => 'Camel in Desert',
                'registration_number' => 'PP/064/2017',
                'is_active' => true,
            ],
            [
                'name' => 'Empowerment and Liberation Party',
                'abbreviation' => 'ELP',
                'party_symbol' => 'Ring with people holding hands in unison',
                'registration_number' => 'PP/063/2017',
                'is_active' => true,
            ],
            [
                'name' => 'Ukweli Party',
                'abbreviation' => 'UP',
                'party_symbol' => 'U-shaped green plant',
                'registration_number' => 'PP/061/2017',
                'is_active' => true,
            ],
            [
                'name' => 'Alternative Leadership Party Of Kenya',
                'abbreviation' => 'ALPK',
                'party_symbol' => 'Burning Candle with an orange flame',
                'registration_number' => 'PP/060/2017',
                'is_active' => true,
            ],
            [
                'name' => 'Movement for Democracy and Growth',
                'abbreviation' => 'MDG',
                'party_symbol' => 'Three fresh maize cobs in their safety husks',
                'registration_number' => 'PP/059/2017',
                'is_active' => true,
            ],
            [
                'name' => 'National Liberal Party',
                'abbreviation' => 'NLP',
                'party_symbol' => 'Giraffe',
                'registration_number' => 'PP/058/2017',
                'is_active' => true,
            ],
            [
                'name' => 'Green Congress of Kenya',
                'abbreviation' => 'GCK',
                'party_symbol' => 'Five Green Trees',
                'registration_number' => 'PP/057/2017',
                'is_active' => true,
            ],
            [
                'name' => 'Liberal Democratic Party',
                'abbreviation' => 'LDP',
                'party_symbol' => 'Satellite Dish',
                'registration_number' => 'PP/056/2017',
                'is_active' => true,
            ],
            [
                'name' => 'Democratic Congress',
                'abbreviation' => 'DC',
                'party_symbol' => 'Butterfly',
                'registration_number' => 'PP/055/2017',
                'is_active' => true,
            ],
            [
                'name' => 'Maendeleo Chap Chap',
                'abbreviation' => 'MCC',
                'party_symbol' => 'Road',
                'registration_number' => 'PP/054/2017',
                'is_active' => true,
            ],
            [
                'name' => 'People\'s Trust Party',
                'abbreviation' => 'PTP',
                'party_symbol' => 'Arrow',
                'registration_number' => 'PP/053/2017',
                'is_active' => true,
            ],
            [
                'name' => 'Kenya Reform Party',
                'abbreviation' => 'KRP',
                'party_symbol' => 'Mechanical gear and shaft',
                'registration_number' => 'PP/052/2017',
                'is_active' => true,
            ],
            [
                'name' => 'United Democratic Party',
                'abbreviation' => 'UDP',
                'party_symbol' => 'Shield',
                'registration_number' => 'PP/051/2017',
                'is_active' => true,
            ],
            [
                'name' => 'Devolution Party of Kenya',
                'abbreviation' => 'DPK',
                'party_symbol' => 'Tap with running water',
                'registration_number' => 'PP/050/2017',
                'is_active' => true,
            ],
            [
                'name' => 'Ubuntu People\'s Forum',
                'abbreviation' => 'UPF',
                'party_symbol' => 'Double thumbs up',
                'registration_number' => 'PP/049/2017',
                'is_active' => true,
            ],
            [
                'name' => 'Vibrant Democracy Party',
                'abbreviation' => 'VDP',
                'party_symbol' => 'Eagle',
                'registration_number' => 'PP/048/2017',
                'is_active' => true,
            ],
            [
                'name' => 'Roots Party of Kenya',
                'abbreviation' => 'RPK',
                'party_symbol' => 'Tree and Roots',
                'registration_number' => 'PP/047/2017',
                'is_active' => true,
            ],
            [
                'name' => 'Republican Liberty Party',
                'abbreviation' => 'RLP',
                'party_symbol' => 'Horse',
                'registration_number' => 'PP/046/2017',
                'is_active' => true,
            ],
            [
                'name' => 'Forum For Republican Democracy -Asili',
                'abbreviation' => 'FORD-A',
                'party_symbol' => 'Two raised fingers inside the Kenyan Map',
                'registration_number' => 'PP/045/2017',
                'is_active' => true,
            ],
            [
                'name' => 'Alliance for Real Change',
                'abbreviation' => 'ARC',
                'party_symbol' => 'Aeroplane with the Party Name',
                'registration_number' => 'PP/044/2017',
                'is_active' => true,
            ],
            [
                'name' => 'Chama Cha Mashinani',
                'abbreviation' => 'CCM',
                'party_symbol' => 'Golden Yellow Trumpet',
                'registration_number' => 'PP/043/2016',
                'is_active' => true,
            ],
            [
                'name' => 'Jirani Mzalendo Asili Party of Kenya',
                'abbreviation' => 'JMAPK',
                'party_symbol' => 'Red shoe',
                'registration_number' => 'PP/042/2016',
                'is_active' => true,
            ],
            [
                'name' => 'The National Party',
                'abbreviation' => 'TNP',
                'party_symbol' => 'Book',
                'registration_number' => 'PP/041/2016',
                'is_active' => true,
            ],
            [
                'name' => 'Muungano Party',
                'abbreviation' => 'MP',
                'party_symbol' => 'Interlocked Rings',
                'registration_number' => 'PP/040/2016',
                'is_active' => true,
            ],
            [
                'name' => 'Federal Party of Kenya',
                'abbreviation' => 'FPK',
                'party_symbol' => 'Fist',
                'registration_number' => 'PP/039/2016',
                'is_active' => true,
            ],
            [
                'name' => 'Economic Freedom Party',
                'abbreviation' => 'EFP',
                'party_symbol' => 'Acacia tree',
                'registration_number' => 'PP/038/2016',
                'is_active' => true,
            ],
            [
                'name' => 'Farmers Party',
                'abbreviation' => 'FP',
                'party_symbol' => 'Maize Plant',
                'registration_number' => 'PP/037/2016',
                'is_active' => true,
            ],
            [
                'name' => 'United Party of Independent Alliance',
                'abbreviation' => 'UPIA',
                'party_symbol' => 'Antelope',
                'registration_number' => 'PP/036/2016',
                'is_active' => true,
            ],
            [
                'name' => 'Umoja na Maendeleo Party',
                'abbreviation' => 'UMP',
                'party_symbol' => 'Factory',
                'registration_number' => 'PP/035/2016',
                'is_active' => true,
            ],
            [
                'name' => 'Party of Democratic Unity',
                'abbreviation' => 'PDU',
                'party_symbol' => 'Drum',
                'registration_number' => 'PP/034/2016',
                'is_active' => true,
            ],
            [
                'name' => 'Shirikisho Party of Kenya',
                'abbreviation' => 'SPK',
                'party_symbol' => 'Shark',
                'registration_number' => 'PP/033/2016',
                'is_active' => true,
            ],
            [
                'name' => 'United Democratic Movement',
                'abbreviation' => 'UDM',
                'party_symbol' => 'Goat',
                'registration_number' => 'PP/032/2016',
                'is_active' => true,
            ],
            [
                'name' => 'The New Democrats',
                'abbreviation' => 'TND',
                'party_symbol' => 'Bridge',
                'registration_number' => 'PP/031/2016',
                'is_active' => true,
            ],
            [
                'name' => 'Peoples Democratic Party',
                'abbreviation' => 'PDP',
                'party_symbol' => 'Traditional African Banjo',
                'registration_number' => 'PP/030/2016',
                'is_active' => true,
            ],
            [
                'name' => 'People\'s Empowerment Party',
                'abbreviation' => 'PEP',
                'party_symbol' => 'Elephant',
                'registration_number' => 'PP/029/2016',
                'is_active' => true,
            ],
            [
                'name' => 'National Agenda Party of Kenya',
                'abbreviation' => 'NAPK',
                'party_symbol' => 'A teacher pointing at a blackboard',
                'registration_number' => 'PP/028/2016',
                'is_active' => true,
            ],
            [
                'name' => 'Chama Cha Uzalendo',
                'abbreviation' => 'CCU',
                'party_symbol' => 'Security Whistle',
                'registration_number' => 'PP/027/2016',
                'is_active' => true,
            ],
            [
                'name' => 'Safina Party',
                'abbreviation' => 'SP',
                'party_symbol' => 'Ark carrying animals and people',
                'registration_number' => 'PP/026/1996',
                'is_active' => true,
            ],
            [
                'name' => 'Communist Party of Kenya',
                'abbreviation' => 'CPK',
                'party_symbol' => 'Hammer crossed with a sickle',
                'registration_number' => 'PP/025/2008',
                'is_active' => true,
            ],
            [
                'name' => 'Kenya Patriots Party',
                'abbreviation' => 'KPP',
                'party_symbol' => 'Wheel',
                'registration_number' => 'PP/024/2008',
                'is_active' => true,
            ],
            [
                'name' => 'Kenya African Democratic Union-Asili',
                'abbreviation' => 'KADU-A',
                'party_symbol' => 'Coconut Tree',
                'registration_number' => 'PP/023/1991',
                'is_active' => true,
            ],
            [
                'name' => 'Maendeleo Democratic Party',
                'abbreviation' => 'MDP',
                'party_symbol' => 'Scissors',
                'registration_number' => 'PP/022/2007',
                'is_active' => true,
            ],
            [
                'name' => 'Progressive Party of Kenya',
                'abbreviation' => 'PPK',
                'party_symbol' => 'Battery Torch',
                'registration_number' => 'PP/021/2007',
                'is_active' => true,
            ],
            [
                'name' => 'People\'s Party of Kenya',
                'abbreviation' => 'PPK2',
                'party_symbol' => 'Microphone',
                'registration_number' => 'PP/020/2007',
                'is_active' => true,
            ],
            [
                'name' => 'Kenya Social Congress',
                'abbreviation' => 'KSC',
                'party_symbol' => 'Broom',
                'registration_number' => 'PP/019/2007',
                'is_active' => true,
            ],
            [
                'name' => 'Agano Party',
                'abbreviation' => 'AP',
                'party_symbol' => 'Lamb',
                'registration_number' => 'PP/018/2012',
                'is_active' => true,
            ],
            [
                'name' => 'Party of National Unity',
                'abbreviation' => 'PNU',
                'party_symbol' => 'Two torches with flames',
                'registration_number' => 'PP/017/2007',
                'is_active' => true,
            ],
            [
                'name' => 'Democratic Party of Kenya',
                'abbreviation' => 'DPK2',
                'party_symbol' => 'Lantern',
                'registration_number' => 'PP/016/1991',
                'is_active' => true,
            ],
            [
                'name' => 'Kenya Moja Movement Party',
                'abbreviation' => 'KMMP',
                'party_symbol' => 'Sunflower',
                'registration_number' => 'PP/015/2007',
                'is_active' => true,
            ],
            [
                'name' => 'Mazingira Green Party',
                'abbreviation' => 'MGP',
                'party_symbol' => 'Tree',
                'registration_number' => 'PP/014/2003',
                'is_active' => true,
            ],
            [
                'name' => 'Kenya National Congress',
                'abbreviation' => 'KNC',
                'party_symbol' => 'Key',
                'registration_number' => 'PP/013/2007',
                'is_active' => true,
            ],
            [
                'name' => 'Devolution Empowerment Party',
                'abbreviation' => 'DEP',
                'party_symbol' => 'Bus',
                'registration_number' => 'PP/011/2012',
                'is_active' => true,
            ],
            [
                'name' => 'Party of Independent Candidate of Kenya',
                'abbreviation' => 'PICK',
                'party_symbol' => 'Child being lifted by both hands',
                'registration_number' => 'PP/010/2007',
                'is_active' => true,
            ],
            [
                'name' => 'Mwangaza Party',
                'abbreviation' => 'MP2',
                'party_symbol' => 'House',
                'registration_number' => 'PP/009/2007',
                'is_active' => true,
            ],
            [
                'name' => 'Labour Party of Kenya',
                'abbreviation' => 'LPK',
                'party_symbol' => 'Star',
                'registration_number' => 'PP/008/1996',
                'is_active' => true,
            ],
            [
                'name' => 'The National Vision Party',
                'abbreviation' => 'TNVP',
                'party_symbol' => 'Light House',
                'registration_number' => 'PP/007/2007',
                'is_active' => true,
            ],
            [
                'name' => 'People\'s Liberation Party',
                'abbreviation' => 'PLP',
                'party_symbol' => 'Purple Rose',
                'registration_number' => 'PP/006/2007',
                'is_active' => true,
            ],
        ];

        $timestamp = Carbon::now();
        
        foreach ($parties as $party) {
            $party['created_at'] = $timestamp;
            $party['updated_at'] = $timestamp;
        }

        DB::table('political_parties')->insert($parties);
    }
}
